" vim:ft=vim:et:sw=2:sts=-1
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim
runtime xdg.vim

scriptencoding utf-8

" Mainly for easymotion
" To enable it :packadd vim-easymotion
let mapleader="\<Space>"

" Colours
augroup colourTweaks
  autocmd!
  autocmd ColorScheme * hi Comment cterm=italic

  autocmd ColorScheme space-vim-dark
        \ hi Normal ctermbg=NONE guibg=NONE |
        \ hi LineNr ctermbg=NONE guibg=NONE |
        \ hi SignColumn ctermbg=NONE guibg=NONE

  " g:codedark_italics is already taken care of above
  autocmd ColorSchemePre codedark let g:codedark_transparent=1
augroup END
set cursorline cursorlineopt=number
colorscheme space-vim-dark

" Windows & buffers
set cmdheight=2
if has('patch-8.2.4325') | set wildoptions+=pum | endif
if has('patch-8.2.4463') | set wildoptions+=fuzzy | endif
if has('patch-7.4.0775')
   " <https://github.com/vim/vim/issues/2877>
   " `no{insert,select}` without `menuone` (7.0.0213) is useless:
  set completeopt+=noselect,menuone
endif
if has('patch-9.1.0463') | set completeopt+=fuzzy | endif
if has('patch-9.1.1590')
  set complete+=o " since 9.1.1301
  set autocomplete
endif
set confirm
set hidden
set number relativenumber
set laststatus=2 " 2=always show
if has('patch-8.1.1270') | set shortmess-=S | endif " S=hide match number of search

set statusline=
set statusline+=%2n%h%w%r%{&modified?'✦':'\ '}%*%.30f%<\ 
set statusline+=%{strlen(&filetype)?&filetype:'-'}\ 
set statusline+=%{&fileformat}\ 
set statusline+=%{strlen(&fenc)?&fenc:&enc}
set statusline+=%{%&bomb?'%#ErrorMsg#-bom':''%}%*
set statusline+=%{%&eol?'↩':'%#ErrorMsg#¶'%}%*
set statusline+=%=%l:%c\ U+%04B\ %P

" Whitespace
set list
set listchars=lead:·,trail:·,nbsp:␣,tab:⇄\ ,precedes:←,extends:→

" Search
"  Incremental search is enabled in the defaults, so let's enable highlighting
"  and let's use Ctrl+L to unhighlight
set hlsearch
nnoremap <silent> <C-l> :nohlsearch<CR><C-l>

" Bundled opt packages
if has('patch-7.4.1649') | packadd matchit | endif
if has('patch-9.0.1799')
  packadd editorconfig
  " cf. <https://github.com/vim/vim/blob/8c93e2d50dacabcd66cc4cb9573da497e98d3c26/runtime/pack/dist/opt/editorconfig/doc/editorconfig.txt#L62-L73>
  " otherwise git commit messages can be affected
  augroup handsOffMyGitEditorconfig
    autocmd!
    autocmd FileType gitcommit let b:EditorConfig_disable = 1
  augroup END
endif
if has('patch-9.1.0375') | packadd comment | endif
if has('patch-9.1.0497') | packadd nohlsearch | endif
if has('patch-9.1.0831')
  if !exists('g:helptoc')
    let g:helptoc = {'shell_prompt': '^[a-zA-Z0-9-_.]\+@[a-zA-Z0-9-_.]\+ [^>]\+>\+ '} " default fish prompt
  endif
  packadd helptoc
  nnoremap <silent> <Leader>t :HelpToc<CR>
endif
if has('patch-9.1.1228')
  packadd hlyank
  let g:hlyank_duration = 5000
endif
